assessors:
  fuji:
    enabled: true
    class: "fair_assessment_proxy.plugins.fuji.FujiAssessor"
    name: "F-UJI"
    version: "3.5.0"
    base_url: "http://fuji:1071/fuji/api/v1"

    cached_mode:
      metadata_service_endpoint: "http://metadata-gateway:3000/oai"
      metadata_service_type: "oai_pmh"

  fair_champion:
    enabled: true
    class: "fair_assessment_proxy.plugins.fair_champion.FairChampionAssessor"
    name: "FAIR Champion"
    version: "0.5.8"
    service_version: "1.1.11"
    champion_base_url: "http://fair-champion:4567/champion"
    algorithm: "1UvHnRkKy3KZMlWdIdB7rz0LrBZJXpPibAgmTXJwRO_0"
    metadata_gateway_base_url: "http://metadata-gateway:3000"
