assessors:
  fuji:
    enabled: true
    class: "fair_assessment_proxy.plugins.fuji.FujiAssessor"
    name: "F-UJI"
    base_url: "http://fuji:1071/fuji/api/v1"

    cached_mode:
      metadata_service_endpoint: "http://metadata-gateway:3000/oai"
      metadata_service_type: "oai_pmh"

  fair_champion:
    enabled: true
    class: "fair_assessment_proxy.plugins.fair_champion.FairChampionAssessor"
    name: "FAIR Champion"
    champion_base_url: "http://fair-champion:4567/champion"
    fair_core_tests_base_url: "http://fair-core-tests:8282/tests"
    metadata_gateway_base_url: "http://metadata-gateway:3000"

